name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-to-pypi:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/gr-aggregation 
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          python -m build 
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
